In [1]:
from tinygrad.densetensor import DenseTensor
from tinygrad.sparsetensor import SparseTensor
import numpy as np
import tinygrad.optim as optim
from extra.utils import get_parameters


%load_ext autoreload
%autoreload 2

DEVICE:GPU


In [2]:
seedmat = np.random.randn(3,3).astype(np.float32)

In [3]:
x_init = np.random.randn(1,3).astype(np.float32)
x = DenseTensor(x_init)
y = DenseTensor(np.ones((3,1)))

warning, (3, 1) isn't float32, it's float64


In [4]:
class MLP:
  def __init__(self):
    self.W = DenseTensor(seedmat)

  def parameters(self):
    return get_parameters(self)

  def forward(self, x):
    out = self.W.dot(x.transpose())#.relu()
    #out = out.logsoftmax()
    #out = out.mul(self.m).add(self.m).sum()
    return out

In [5]:
class MLP2:
  def __init__(self):
    self.W = SparseTensor(seedmat)

  def parameters(self):
    return get_parameters(self)

  def forward(self, x):
    out = self.W.dot(x.transpose())#.relu()
    #out = out.logsoftmax()
    #out = out.mul(self.m).add(self.m).sum()
    return out

In [6]:
def loss_fn(y, y_pred):
    return ((y-y_pred)**2)**.5

### Dense

In [7]:
model = MLP()

In [8]:
optimizer = optim.SGD(model.parameters(), lr=.0001)

In [9]:
optimizer.zero_grad()
res = model.forward(x)
loss = loss_fn(res, y)
loss.backward()
#optimizer.step()

In [10]:
model.parameters()

[<DenseTensor <GPUBuffer with shape (3, 3)> with grad <GPUBuffer with shape (3, 3)>>,
 <DenseTensor <GPUBuffer with shape (3, 3)> with grad None>]

In [11]:
loss.cpu().data

array([[1.0780131],
       [1.4028268],
       [2.5222237]], dtype=float32)

In [12]:
res.cpu().data

array([[-0.07801307],
       [-0.40282673],
       [ 3.5222237 ]], dtype=float32)

In [13]:
res.grad.cpu().data

array([[-0.99999994],
       [-1.        ],
       [ 1.        ]], dtype=float32)

In [14]:
model.W.grad.cpu().data

array([[ 2.252644  , -0.38438952,  0.02865383],
       [ 2.2526443 , -0.38438955,  0.02865383],
       [-2.2526443 ,  0.38438955, -0.02865383]], dtype=float32)

### Second

In [15]:
model = MLP2()

In [16]:
optimizer = optim.SGD(model.parameters(), lr=.0001)

In [17]:
optimizer.zero_grad()
res = model.forward(x)
loss = loss_fn(res, y)
loss.backward()
#optimizer.step()

In [18]:
loss.cpu().data

array([[1.0780131],
       [1.4028268],
       [2.5222237]], dtype=float32)

In [19]:
res.cpu().data

array([[-0.07801307],
       [-0.40282673],
       [ 3.5222237 ]], dtype=float32)

In [20]:
res.grad.cpu().data

array([[-0.99999994],
       [-1.        ],
       [ 1.        ]], dtype=float32)

In [21]:
model.W.grad.cpu().data

array([[ 2.252644  , -0.38438952,  0.02865383],
       [ 2.2526443 , -0.38438955,  0.02865383],
       [-2.2526443 ,  0.38438955, -0.02865383]], dtype=float32)

In [20]:
res.cpu().data

array([[ 0.64451325],
       [ 1.7452391 ],
       [-0.63733023]], dtype=float32)