In [1]:
from tinygrad.densetensor import DenseTensor
from tinygrad.sparsetensor import SparseTensor
import numpy as np

%load_ext autoreload
%autoreload 2

TRY GPU
DEVICE:GPU


In [2]:
x_init = np.random.randn(1,3).astype(np.float32)
x2_init = np.random.randn(3).astype(np.float32)
U_init = np.random.randn(3,3).astype(np.float32)
V_init = np.random.randn(3,3).astype(np.float32)
W_init = np.random.randn(3,3).astype(np.float32)
m_init = np.random.randn(1,3).astype(np.float32)

In [3]:
x = DenseTensor(x_init)
W = DenseTensor(W_init)
m = DenseTensor(m_init)
out = x.dot(W).relu()
out = out.logsoftmax()
out = out.mul(m).add(m).sum()
out.backward()

out.cpu().data, x

dense shape grad; (1,)
PRT: (<DenseTensor <GPUBuffer with shape (1, 3)> with grad None>,)
GRDS: [<GPUBuffer with shape (1, 3)>]
T/g: <DenseTensor <GPUBuffer with shape (1, 3)> with grad None> <GPUBuffer with shape (1, 3)>
PRT: (<DenseTensor <GPUBuffer with shape (1, 3)> with grad None>, <DenseTensor <GPUBuffer with shape (1, 3)> with grad None>)
GRDS: (<GPUBuffer with shape (1, 3)>, <GPUBuffer with shape (1, 3)>)
T/g: <DenseTensor <GPUBuffer with shape (1, 3)> with grad None> <GPUBuffer with shape (1, 3)>
T/g: <DenseTensor <GPUBuffer with shape (1, 3)> with grad None> <GPUBuffer with shape (1, 3)>
PRT: (<DenseTensor <GPUBuffer with shape (1, 3)> with grad None>, <DenseTensor <GPUBuffer with shape (1, 3)> with grad <GPUBuffer with shape (1, 3)>>)
GRDS: (<GPUBuffer with shape (1, 3)>, <GPUBuffer with shape (1, 3)>)
T/g: <DenseTensor <GPUBuffer with shape (1, 3)> with grad None> <GPUBuffer with shape (1, 3)>
T/g: <DenseTensor <GPUBuffer with shape (1, 3)> with grad <GPUBuffer with shape (

(array([1.3010626], dtype=float32),
 <DenseTensor <GPUBuffer with shape (1, 3)> with grad <GPUBuffer with shape (1, 3)>>)

In [4]:
x2 = DenseTensor(x2_init)#.gpu()
W = SparseTensor(W_init)
out = W.dot(x2).relu()

out.backward()

out.cpu().data, x

[[ 1.6416572  -1.1452918  -0.40320277]
 [ 0.9028812  -1.8745078  -0.6020789 ]
 [-1.4252311   1.4327703   0.9681495 ]]
dense shape grad; (3,)
aval, xval: 1.64,-0.94:0-0 
aval, xval: 0.90,-0.94:0-3 
aval, xval: -1.43,-0.94:0-6 
aval, xval: -1.15,-0.42:1-1 
aval, xval: -1.87,-0.42:1-4 
aval, xval: 1.43,-0.42:1-7 
aval, xval: -0.40,0.62:2-2 
aval, xval: -0.60,0.62:2-5 
aval, xval: 0.97,0.62:2-8 
SUM/NNZ: -1.30 3 
SUM/NNZ: -0.42 3 
SUM/NNZ: 1.32 3 
PRT: (<DenseTensor <GPUBuffer with shape (3,)> with grad None>,)
GRDS: [<GPUBuffer with shape (3,)>]
T/g: <DenseTensor <GPUBuffer with shape (3,)> with grad None> <GPUBuffer with shape (3,)>
aval, xval: 1.64,0.00:0-0 
aval, xval: -1.15,0.00:0-3 
aval, xval: -0.40,0.00:0-6 
aval, xval: 0.90,0.00:1-1 
aval, xval: -1.87,0.00:1-4 
aval, xval: -0.60,0.00:1-7 
aval, xval: -1.43,1.00:2-2 
aval, xval: 1.43,1.00:2-5 
aval, xval: 0.97,1.00:2-8 
SUM/NNZ: -1.43 3 
SUM/NNZ: 1.43 3 
SUM/NNZ: 0.97 3 
PRT: (<SparseTensor <GPUBuffer with shape (9,)> with grad Non

(array([0.       , 0.       , 1.3227259], dtype=float32),
 <DenseTensor <GPUBuffer with shape (1, 3)> with grad <GPUBuffer with shape (1, 3)>>)