In [1]:
from tinygrad.densetensor import DenseTensor
from tinygrad.sparsetensor import SparseTensor
import numpy as np
import tinygrad.optim as optim

%load_ext autoreload
%autoreload 2

DEVICE:GPU


In [10]:
dim1 = 3
dim2 = 3
dim3 = 3

x_init = np.random.randn(3,3).astype(np.float32)
x2_init = np.random.randn(3).astype(np.float32)
U_init = np.random.randn(3,3).astype(np.float32)
V_init = np.random.randn(3,3).astype(np.float32)
W_init = SparseTensor.uniform(dim2,dim3, randsparsity=0.7).to_numpy().astype(np.float32)
m_init = np.random.randn(1,3).astype(np.float32)

In [11]:
x_init

array([[ 0.110732  ,  0.18753076,  0.3077455 ],
       [-0.4032947 ,  0.12086255,  0.69365877],
       [ 0.47443777,  0.43354484, -0.82397753]], dtype=float32)

In [12]:
W_init

array([[0.        , 0.        , 0.00196458],
       [0.00484476, 0.        , 0.        ],
       [0.00826782, 0.        , 0.        ]], dtype=float32)

In [13]:
x = DenseTensor(x_init)
W = DenseTensor(W_init)
m = DenseTensor(m_init)
out = x.dot(W).relu()
out = out.logsoftmax()
out = out.mul(m).add(m).sum()
out.backward()

out.cpu().data, x

(array([0.5524663], dtype=float32),
 <DenseTensor <GPUBuffer with shape (3, 3)> with grad <GPUBuffer with shape (3, 3)>>)

In [14]:
x = SparseTensor(x_init.T)
W = DenseTensor(W_init.T)
m = DenseTensor(m_init)
out = x.dot(W).relu()
out = out.logsoftmax()
out = out.mul(m).add(m).sum()
out.backward()

out.cpu().data, x

(array([0.5624094], dtype=float32),
 <SparseTensor <GPUBuffer with shape (9,)> with grad <DenseTensor <GPUBuffer with shape (3, 3)> with grad None>>)

In [15]:
dim = 16
x2 = DenseTensor(np.random.randn(dim,1).astype(np.float32))#.gpu()
W = SparseTensor(randinit=(dim,dim), randsparsity=0.2)
out = W.dot(x2).relu()

out.backward()

out.cpu().data, out.cpu().data.shape

(array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.80540252e-02,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.23650008e-03,
         1.54125830e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [4.49533155e-03, 6.44196942e-03, 5.00780530e-03, 0.00000000e+00,
         3.85948806e-03, 1.26029486e-02, 1.54838711e-02, 1.43047022e-02,
         1.77512988e-02, 1.43454298e-02, 1.08837029e-02, 0.00000000e+00,
         0.00000000e+00, 1.32352794e-02, 1.20087350e-02, 2.31401017e-03],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.34245220e-04,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.57728116e-05,
         4.56081063e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.33023495e-04, 1.90627368e-04, 1.48188337e-04, 0.00000000e+00,
         1.14207935e-04, 3.72939830e-04, 4.58190

In [8]:
out.grad.cpu().data

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)