In [1]:
from tinygrad.densetensor import DenseTensor
from tinygrad.sparsetensor import SparseTensor
import numpy as np
import tinygrad.optim as optim

%load_ext autoreload
%autoreload 2

DEVICE:GPU


In [2]:
x_init = np.random.randn(3,3).astype(np.float32)
x2_init = np.random.randn(3).astype(np.float32)
U_init = np.random.randn(3,3).astype(np.float32)
V_init = np.random.randn(3,3).astype(np.float32)
W_init = np.random.randn(3,3).astype(np.float32)
m_init = np.random.randn(1,3).astype(np.float32)

In [3]:
x_init

array([[ 0.01603718,  0.20646408, -1.4635118 ],
       [-0.04414416, -0.03207636, -1.038237  ],
       [-0.8905831 ,  0.13894197, -0.06180749]], dtype=float32)

In [4]:
W_init

array([[-1.280417  ,  1.0253801 ,  1.4955127 ],
       [ 0.8052573 ,  0.04673147, -0.8061982 ],
       [ 0.33840021, -1.061602  ,  0.247293  ]], dtype=float32)

In [5]:
x = DenseTensor(x_init)
W = DenseTensor(W_init)
m = DenseTensor(m_init)
out = x.dot(W).relu()
out = out.logsoftmax()
out = out.mul(m).add(m).sum()
out.backward()

out.cpu().data, x

(array([2.1259818], dtype=float32),
 <DenseTensor <GPUBuffer with shape (3, 3)> with grad <GPUBuffer with shape (3, 3)>>)

In [6]:
x = SparseTensor(x_init.T)
W = DenseTensor(W_init.T)
m = DenseTensor(m_init)
out = x.dot(W).relu()
out = out.logsoftmax()
out = out.mul(m).add(m).sum()
out.backward()

out.cpu().data, x

WEIGHT/input: <SparseTensor <GPUBuffer with shape (9,)> with grad None> <GPUBuffer with shape (3, 3)>
warning, (3, 3) isn't float32, it's float64


(array([2.1259818], dtype=float32),
 <SparseTensor <GPUBuffer with shape (9,)> with grad <DenseTensor <GPUBuffer with shape (3, 3)> with grad None>>)

In [7]:
dim = 16
x2 = DenseTensor(np.random.randn(dim,1).astype(np.float32))#.gpu()
W = SparseTensor(randinit=(dim,dim), randsparsity=0.2)
out = W.dot(x2).relu()

out.backward()

out.cpu().data, out.cpu().data.shape

WEIGHT/input: <SparseTensor <GPUBuffer with shape (448,)> with grad None> <GPUBuffer with shape (16, 1)>


(array([[0.35385808],
        [1.3043803 ],
        [0.5843513 ],
        [0.11474065],
        [0.6444051 ],
        [0.2517727 ],
        [0.        ],
        [0.5577746 ],
        [0.5868567 ],
        [0.41644603],
        [1.1289623 ],
        [0.71064   ],
        [0.16699183],
        [1.2362077 ],
        [0.27970877],
        [0.9728807 ]], dtype=float32),
 (16, 1))

In [8]:
out.grad.cpu().data

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)