In [17]:
from tinygrad.densetensor import DenseTensor
from tinygrad.sparsetensor import SparseTensor
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [18]:
x_init = np.random.randn(1,3).astype(np.float32)
x2_init = np.random.randn(3).astype(np.float32)
U_init = np.random.randn(3,3).astype(np.float32)
V_init = np.random.randn(3,3).astype(np.float32)
W_init = np.random.randn(3,3).astype(np.float32)
m_init = np.random.randn(1,3).astype(np.float32)

In [19]:
x = DenseTensor(x_init)
W = DenseTensor(W_init)
m = DenseTensor(m_init)
out = x.dot(W).relu()
out = out.logsoftmax()
out = out.mul(m).add(m).sum()
out.backward()

out.cpu().data, x

(array([1.7038704], dtype=float32),
 <DenseTensor <GPUBuffer with shape (1, 3)> with grad <GPUBuffer with shape (1, 3)>>)

In [20]:
bs = 4
dim = 8

x_init = np.random.randn(bs,dim).astype(np.float32)

x2 = DenseTensor(x_init)#.gpu()
W = SparseTensor.uniform(dim,dim, randsparsity=0.6, bs=bs)
out = W.dot(x2).relu()
out = W.dot(out).relu()
out = W.dot(out).relu()
out = W.dot(out).relu()
out = W.dot(out).relu()
out = W.dot(out).relu()

out.backward()

out.cpu().data, out.cpu().data.shape

(array([[5.48265362e+00, 2.03909588e+00, 3.19523525e+00, 2.96530652e+00,
         3.49676870e-02, 1.02712333e+00, 6.31113350e-01, 1.40761197e-01],
        [3.78959937e+03, 1.56201501e+03, 3.17872192e+03, 1.21048281e+04,
         6.52186737e+01, 1.11782349e+03, 4.99647156e+02, 4.34063477e+02],
        [2.73192188e+04, 3.04065723e+03, 6.25770557e+03, 7.45633594e+04,
         4.13716278e+02, 3.79873853e+03, 6.76921387e+02, 2.24331470e+03],
        [6.82212256e+03, 1.10557886e+03, 2.18046191e+03, 1.51809639e+04,
         1.01095604e+02, 9.92445068e+02, 2.93977875e+02, 5.90937073e+02]],
       dtype=float32),
 (4, 8))

In [21]:
dim = 16
x2 = DenseTensor(np.random.randn(1,dim).astype(np.float32))#.gpu()
W = SparseTensor(randinit=(dim,dim), randsparsity=0.2)
out = W.dot(x2).relu()

out.backward()

out.cpu().data, out.cpu().data.shape

(array([[ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      , 15.983707,  0.      ,  0.      ,  0.      ,
          0.      ,  0.      ,  0.      ,  0.      ]], dtype=float32),
 (1, 16))